version: '3.7'

services:
    traefik:
        image: traefik:1.7.14-alpine
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.toml:/traefik.toml
            - ./acme.json:/acme.json
        networks:
          - proxy
        ports:
            - 80:80
            - 443:443
        labels:
            - traefik.frontend.rule=Host:${TRAEFIK_FRONTEND_HOST}
            - traefik.port=8080
        command: --docker
        tty: true

networks:
    proxy:
        external: true
